# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API = 2
VAGRANT_WP_DOMAIN_NAME = ENV['VAGRANT_WP_DOMAIN_NAME'] || "example.site"
VAGRANT_WP_PASS = ENV['VAGRANT_WP_PASS'] || "vagrant"
VAGRANT_WP_SITE_TITLE = ENV['VAGRANT_WP_SITE_TITLE'] || "Example Site"
VAGRANT_WP_USER = ENV['VAGRANT_WP_USER'] || "webmaster"

Vagrant.configure(VAGRANT_API) do |config|

    config.vm.box = "ubuntu/bionic64"
    config.vm.network "forwarded_port", guest: 80, host:8009
    config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)", ip: "192.168.1.171"
    config.vm.provision "shell", path: "deploy/vagrant.sh", args: [VAGRANT_WP_DOMAIN_NAME, VAGRANT_WP_SITE_TITLE, VAGRANT_WP_USER, VAGRANT_WP_PASS]

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end

end
